source 'https://rubygems.org'
ruby '1.9.3'

gem 'dm-core', '>=1.2'
gem 'dm-migrations', '>=1.2'
gem 'dm-sqlite-adapter', '>=1.2'
gem 'dm-timestamps', '>=1.2'
gem 'dm-validations', '>=1.2'
gem 'multi_json', '>=1.7'
gem 'net-http-digest_auth', '>=1.4'
gem 'rack-recaptcha', '>=0.6'
gem 'rack-test', '>=0.6'
gem 'sinatra', '>=1.4'
gem 'sinatra-contrib', '>=1.4'
gem 'syntaxi', '>=0.5'
gem 'yajl-ruby', '>=1.1'
